org: gudongfeng
app: object-detection
# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-mxnet

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: python3.6
  timeout: 30
  region: us-east-1
  # Provide permissions for this service to manipulate S3.
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetBucketLocation"
      Resource: "arn:aws:s3:::gudongfeng.me/*"

# The `functions` block defines what code to deploy
functions:
  detect:
    handler: handler.detect
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: detect
          method: post 
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
